### ISSUE TITLE
Continuation of this project

### ISSUE THREAD

**Issue by zgiles** [zevlag/pfsense-ports#7]
Hello..
I was wondering if you would mind if some of us work on this project and release some code based on this.. since you listed it as personal dev and I don't see a "License" on it. ( Therefore it is not free... )
If you wouldn't mind, and would be comfortable throwing the MIT license on it or something, I'd be happy to try and build/release an updated version of this.
Thx!
-Zach

**Comment by zevlag** [comment]
https://github.com/zevlag/pfsense-ports/blob/master/LICENSE
